#ifndef NGX_STREAM_TROJAN_IP_PREFER_H
#define NGX_STREAM_TROJAN_IP_PREFER_H

#define NGX_STREAM_TROJAN_IP_PREFER_AUTO 0
#define NGX_STREAM_TROJAN_IP_PREFER_IPV4 1
#define NGX_STREAM_TROJAN_IP_PREFER_IPV6 2

#endif
